name: Build dev

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: Build and upload artifact
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable windows
        run: flutter config --enable-windows-desktop

      - name: Pub get
        run: dart pub get

      - name: Run tests
        run: flutter test

      - name: Build
        run: flutter build windows --debug --target=.\lib\main_dev.dart

      - name: Generate docs
        run: dart doc

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build ${{ github.run_number }}
          path: .\build\windows\runner\Debug

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: Docs ${{ github.run_number }}
          path: .\doc
  docs:
    name: Upload docs
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get docs
        uses: actions/download-artifact@v3
        with:
          name: Docs ${{ github.run_number }}
          
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api