name: "Pre release"

on: [workflow_call]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"
    needs: [build]
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: .\build\windows\runner\Release\*