name: "Pre release"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  pre-release:
    name: "pre-release"
    runs-on: "windows-latest"
    needs: [test]
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter config --enable-windows-desktop

      - run: flutter test

      - run: flutter build windows --release --target=.\lib\main_dev.dart

      - uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Release.zip'
          path: .\build\windows\runner\Release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: Release.zip